# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_main_tab.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1018, 698)
        self.gridLayout_3 = QtWidgets.QGridLayout(Form)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.test_status_table = QtWidgets.QTableWidget(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.test_status_table.sizePolicy().hasHeightForWidth())
        self.test_status_table.setSizePolicy(sizePolicy)
        self.test_status_table.setObjectName("test_status_table")
        self.test_status_table.setColumnCount(1)
        self.test_status_table.setRowCount(6)
        item = QtWidgets.QTableWidgetItem()
        self.test_status_table.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.test_status_table.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.test_status_table.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.test_status_table.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.test_status_table.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.test_status_table.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.test_status_table.setHorizontalHeaderItem(0, item)
        self.test_status_table.horizontalHeader().setDefaultSectionSize(300)
        self.test_status_table.horizontalHeader().setMinimumSectionSize(30)
        self.gridLayout.addWidget(self.test_status_table, 2, 0, 1, 2)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 1, 0, 1, 2)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.test_start_button = QtWidgets.QPushButton(Form)
        self.test_start_button.setObjectName("test_start_button")
        self.gridLayout_2.addWidget(self.test_start_button, 2, 0, 1, 1)
        self.test_stop_button = QtWidgets.QPushButton(Form)
        self.test_stop_button.setObjectName("test_stop_button")
        self.gridLayout_2.addWidget(self.test_stop_button, 2, 1, 1, 1)
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 1, 0, 1, 2)
        self.gridLayout.addLayout(self.gridLayout_2, 0, 0, 1, 1)
        self.register_table = QtWidgets.QTableWidget(Form)
        self.register_table.setRowCount(0)
        self.register_table.setObjectName("register_table")
        self.register_table.setColumnCount(0)
        self.register_table.horizontalHeader().setCascadingSectionResizes(True)
        self.register_table.horizontalHeader().setDefaultSectionSize(150)
        self.register_table.horizontalHeader().setMinimumSectionSize(100)
        self.gridLayout.addWidget(self.register_table, 0, 2, 3, 1)
        self.gridLayout.setColumnStretch(0, 6)
        self.gridLayout.setColumnStretch(2, 7)
        self.gridLayout.setRowStretch(0, 1)
        self.gridLayout.setRowStretch(1, 4)
        self.gridLayout.setRowStretch(2, 5)
        self.gridLayout_3.addLayout(self.gridLayout, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        item = self.test_status_table.verticalHeaderItem(0)
        item.setText(_translate("Form", "Group"))
        item = self.test_status_table.verticalHeaderItem(1)
        item.setText(_translate("Form", "Group Cycle"))
        item = self.test_status_table.verticalHeaderItem(2)
        item.setText(_translate("Form", "Step"))
        item = self.test_status_table.verticalHeaderItem(3)
        item.setText(_translate("Form", "Action"))
        item = self.test_status_table.verticalHeaderItem(4)
        item.setText(_translate("Form", "Stop Judge"))
        item = self.test_status_table.verticalHeaderItem(5)
        item.setText(_translate("Form", "Timeout"))
        item = self.test_status_table.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Value"))
        self.test_start_button.setText(_translate("Form", "START"))
        self.test_stop_button.setText(_translate("Form", "STOP"))
        self.label.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">Test Contol:</span></p></body></html>"))
